import{S,a as b,i as c}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();async function y(s,t,i){const E=`https://pixabay.com/api/?key=42468615-7a21ca39eb8f796f5c09d98b3&q=${s}&image_type=photo&orientation=horizontal&safesearch=${!0}&per_page=${t}&page=${i}`,g=await fetch(E);if(!g.ok)throw new Error("Image error!");return await g.json()}function p(s){return document.querySelector(".gallery"),s.map(({webformatURL:t,largeImageURL:i,tags:n,likes:e,views:r,comments:a,downloads:h})=>`<li class="gallery-item">
            <a href="${i}" class="gallery-link" data-lightbox="gallery">
              <img class="gallery-image"
               src="${t}"
               alt="${n}"/>
               <div class="gallery-text">
              <p>Likes: ${e}</p>
              <p>Views: ${r}</p>
              <p>Comments: ${a}</p>
              <p>Downloads: ${h}</p>
              </div>
            </a>
          </li>`).join("")}const $=document.querySelector(".btn-section"),I=document.querySelector("#data-search");document.querySelector("[data-start]");const l=document.querySelector(".gallery"),m=document.querySelector(".loader"),o=document.querySelector(".load-more-btn"),L=new S(".gallery a",{captionsData:"alt",captionDelay:250});b.defaults.baseURL="https://pixabay.com/api/";let d=1;const f=15;let u="";$.addEventListener("submit",w);o.addEventListener("click",v);async function w(s){if(s.preventDefault(),l.innerHTML="",u=await I.value.trim(),!u){c.warning({title:"Warning",message:"Please enter a search term."}),l.innerHTML="";return}m.classList.remove("is-hidden");try{const t=await y(u,f,d);t.hits.length===0?(o.classList.add("is-hidden"),c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})):(l.innerHTML=p(t.hits),L.refresh(),o.classList.remove("is-hidden"),t.hits.length<15&&o.classList.add("is-hidden"))}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:"An error occurred while fetching images."})}finally{m.classList.add("is-hidden")}}async function v(){m.classList.add("is-hidden"),d+=1;try{const s=await y(u,f,d),t=Math.ceil(s.totalHits/f);l.innerHTML=p(s.hits),L.refresh(),t===d?(o.classList.add("is-hidden"),c.info({title:"Info",message:"We are sorry, but you have reached the end of search results."})):o.classList.remove("is-hidden")}catch(s){console.error("Error fetching more images:",s)}finally{m.classList.add("is-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
