import{S as b,a as v,i as f}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function p(s){const a=`https://pixabay.com/api/?key=42468615-7a21ca39eb8f796f5c09d98b3&q=${s}&image_type=photo&orientation=horizontal&safesearch=${!0}`,c=await fetch(a);if(!c.ok)throw new Error("Image error!");return await c.json()}function h(s){const t=document.querySelector(".gallery");t.innerHTML=s.map(({webformatURL:o,largeImageURL:l,tags:e,likes:r,views:a,comments:c,downloads:g})=>`<li class="gallery-item">
            <a href="${l}" class="gallery-link" data-lightbox="gallery">
              <img class="gallery-image"
               src="${o}"
               alt="${e}"/>
               <div class="gallery-text">
              <p>Likes: ${r}</p>
              <p>Views: ${a}</p>
              <p>Comments: ${c}</p>
              <p>Downloads: ${g}</p>
              </div>
            </a>
          </li>`).join("")}const E=document.querySelector(".btn-section"),S=document.querySelector("#data-search");document.querySelector("[data-start]");const y=document.querySelector(".gallery"),n=document.querySelector(".loader"),i=document.querySelector(".loadMoreBtn"),L=new b(".gallery a",{captionsData:"alt",captionDelay:250});v.defaults.baseURL="https://pixabay.com/api/";let m=1,d=15,M=1,u="";i.classList.remove("loadMoreBtn-visible");E.addEventListener("submit",I);i.addEventListener("click",w);async function I(s){if(s.preventDefault(),y.innerHTML="",u=await S.value.trim(),!u){f.warning({title:"Warning",message:"Please enter a search term."}),y.innerHTML="";return}n.classList.add("loader-visible"),i.classList.add("loadMoreBtn-visible");try{const t=await p(u,m);t.hits.length===0?f.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(h(t.hits),m+=1,M=Math.ceil(t.totalHits/d),L.refresh(),i.classList.remove("loadMoreBtn-visible"))}catch(t){console.error("Error fetching images:",t),f.error({title:"Error",message:"An error occurred while fetching images."})}finally{n.classList.remove("loader-visible")}}async function w(){n.classList.remove("loader-visible");try{const s=await p(u,page);if(s.hits.length>0){const t=(m-1)*d,o=t+d;h(s.hits.slice(t,o)),L.refresh(),m+=1,t+d<s.totalHits?i.classList.add("loadMoreBtn-visible"):i.classList.remove("loadMoreBtn-visible")}else n.classList.remove("loader-visible")}catch(s){console.error("Error fetching more images:",s)}finally{n.classList.remove("loader-visible")}}
//# sourceMappingURL=commonHelpers.js.map
